[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)", "Scattered-Systems (https://gitlab.com/scsys)"]
categories = []
description = "Algae is a collection of core algorithms and data-structures, written in Rust"
edition = "2021"
homepage = "https://github.com/scattered-systems/algae/wiki"
keywords = ["algorithms", "data-structures"]
license = "MIT"
name = "algae-merkle"
readme = "README.md"
repository = "https://github.com/scattered-systems/algae"
version = "0.1.13" # TODO - Update the cargo package version

[features]


[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
blake3 = "1.3.1"
itertools = "0.10.5"
generic-array = "0.14.6"
hex = "0.4.3"
hex-literal = "0.3.4"
log = "0.4.17"
scsys = { git = "https://github.com/scattered-systems/scsys", version = "0.1.25" }
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.87"
sha2 = "0.10.6"
typenum = "1.15.0"

[dev-dependencies]
hex-literal = "0.3.4"
vrf = "0.2.4"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]