[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)", "Scattered-Systems (https://gitlab.com/scsys)"]
categories = []
description = "Algae is a collection of core algorithms and data-structures, written in Rust"
edition = "2021"
homepage = "https://github.com/scattered-systems/algae/wiki"
keywords = ["algorithms", "data-structures"]
license = "MIT"
name = "algae-merkle"
readme = "README.md"
repository = "https://github.com/scattered-systems/algae"
version = "0.1.15" # TODO - Update the cargo package version

[features]


[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
hex = "0.4.3"
itertools = "0.10.5"
log = "0.4.17"
ring = { features = ["wasm32_c"], version = "0.16.20" }
scsys = { features = ["full"], version = "0.1.32" }
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.88"

[dev-dependencies]
hex-literal = "0.3.4"
vrf = "0.2.4"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]