version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /algae
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /graph
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /merkle
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /mmr
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /queue
    schedule:
      interval: daily
