tasks:
  - init: |
      sudo update -y && sudo upgrade -y && sudo autoremove -y
      rustup default nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly
      cargo build --release --target wasm32-unknown-unknown --workspace
    command: cargo watch -x test --all


