tasks:
  - init: rustup default nightly && rustup component add clippy rustfmt && rustup target add wasm32-unknown-unknown wasm32-wasi
      cargo build --release --target wasm32-unknown-unknown --workspace
    command: cargo watch -x test --all


