[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "Algae is a collection of algorithms and data structures optimized for building decentralize systems..."
edition = "2021"
keywords = ["algorithims", "data-structures", "derive"]
license = "MIT"
name = "algae-derive"
readme = "README.md"
repository = "https://github.com/FL03/algae"
version = "0.1.6" # TODO - Update the cargo package version

[lib]
bench = false
crate-type = ["proc-macro"]
test = true

[dependencies]
proc-macro2 = "1.0.40"
quote = "1.0.20"
syn = { features = ["full"], version = "1.0.98" }