[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "algae"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "ds",
    "std",
]

full = [
    "ds",
    "serde",
    "std",
]

# ********* [FF] Dependencies *********
ds = [
    "graph",
    "merkle",
    # "mmr",
]

graph = [
    "dep:algae-graph"
]

merkle = [
    "dep:algae-merkle"
]

# mmr = [
#     "dep:algae-mmr"
# ]

spline = [
    "dep:algae-spline",
]

serde = [
    "algae-core/serde",
    "algae-graph?/serde",
    "algae-merkle?/serde",
]

# ********* [FF] Environments *********
std = [
    "algae-core/std",
    "algae-graph?/std",
]

wasm = []


[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[[example]]
name = "graph"
required-features = ["graph"]


[build-dependencies]

[dependencies]

[dependencies.algae-core]
default-features = false
path = "../core"
version = "0.1.20"

[dependencies.algae-graph]
default-features = false
optional = true
path = "../graph"
version = "0.1.20"

[dependencies.algae-merkle] 
default-features = false
optional = true
path = "../merkle"
version = "0.1.20"

# [dependencies.algae-mmr]
# default-features = false
# optional = true
# path = "../mmr"
# version = "0.1.20"

[dependencies.algae-spline]
default-features = false
optional = true
path = "../spline"
version = "0.1.20"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

