[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "Algae is a collection of algorithms "
edition = "2021"
keywords = ["algorithims"]
license = "MIT"
name = "algae"
readme = "README.md"
repository = "https://github.com/FL03/algae"
version = "0.1.0"

[features]
default = []

[lib]
crate-type = ["cdylib", "rlib"]
name = "lib"
path = "src/lib.rs"
test = true

[[test]]
name = "test"
path = "tests/test.rs"


[dependencies]


