[package]
authors.workspace = true
categories = []
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["algorithms", "data-structures"]
license.workspace = true
name = "algae"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["core"]

core = [
    "merkle", 
    "mmr", 
    "graph"
]

graph = ["algae-graph"]
merkle = ["algae-merkle"]
mmr = ["algae-mmr"]

wasm = []

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dependencies]
algae-graph = { features = [], optional = true, path = "../graph", version = "0.1.18" }
algae-merkle = { features = [], optional = true, path = "../merkle", version = "0.1.18" }
algae-mmr = { features = [], optional = true, path = "../mmr", version = "0.1.18" }
scsys.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
decanter = { features = ["derive"], version = "0.1.3" }
hex-literal = "0.3"
vrf = "0.2"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
