[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)", "Scattered-Systems (https://gitlab.com/scsys)"]
categories = []
description = "Algae is a collection of core algorithms and data-structures, written in Rust"
edition = "2021"
homepage = "https://github.com/scattered-systems/algae/wiki"
keywords = ["algorithms", "data-structures"]
license = "MIT"
name = "algae"
readme = "README.md"
repository = "https://github.com/scattered-systems/algae"
version = "0.1.12" # TODO - Update the cargo package version

[features]
default = ["core", "merkle"]
full = ["core", "merkle"]

core = []
merkle = ["algae-merkle"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[dependencies.algae-merkle]
optional = true
path = "../merkle"
version = "0.1.12"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
