[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "Algae is a collection of algorithms "
edition = "2021"
keywords = ["algorithims"]
license = "MIT"
name = "algae"
readme = "README.md"
repository = "https://github.com/FL03/algae"
version = "0.1.2" # TODO - Update the cargo package version

[features]
default = []

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[[test]]
name = "standard"
path = "tests/standard.rs"

[dependencies]
bson = ">=2.3.0"
config = "0.13.1"
serde = { features = ["derive"], version = ">=1.0.137" }