[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)", "Scattered-Systems (https://gitlab.com/scsys)"]
categories = []
description = "Algae is a collection of core algorithms and data-structures, written in Rust"
edition = "2021"
homepage = "https://github.com/scattered-systems/algae/wiki"
keywords = ["algorithms", "data-structures"]
license = "MIT"
name = "algae"
readme = "README.md"
repository = "https://github.com/scattered-systems/algae"
version = "0.1.15" # TODO - Update the cargo package version

[features]
default = ["core", "graph", "merkle", "mmr"]
full = ["core", "graph", "merkle", "mmr"]

core = ["merkle", "mmr"]
graph = ["algae-graph"]
merkle = ["algae-merkle"]
mmr = ["algae-mmr"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
scsys = { features = [], version = "0.1.28" }
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.88"

[dependencies.algae-graph]
optional = true
path = "../graph"
version = "0.1.15"

[dependencies.algae-merkle]
optional = true
path = "../merkle"
version = "0.1.15"

[dependencies.algae-mmr]
optional = true
path = "../mmr"
version = "0.1.15"


[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
