[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
categories = []
description = "Algae is a collection of core algorithms and data-structures, written in Rust"
edition = "2021"
homepage = "https://scattered-systems.github.io/algae"
keywords = ["algorithms", "data-structures"]
license = "MIT"
name = "algae"
readme = "README.md"
repository = "https://github.com/scattered-systems/algae"
version = "0.1.8" # TODO - Update the cargo package version

[features]
default = []
derive = ["algae-derive"]
full = ["default", "derive", "macros"]
macros = ["algae-macros"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
blake2 = "0.10.4"
bson = "2.3.0"
config = "0.13.1"
digest = "0.10.3"
glob = "0.3.0"
hex = "0.4.3"
log = "0.4.17"
sha2 = "0.10.2"
serde = { features = ["derive"], version = ">=1.0.137" }

[build-dependencies]
algae-derive = { optional = true, path = "../derive", version = "0.1.7" }
algae-macros = { optional = true, path = "../macros", version = "0.1.7" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]