[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "Algae is a collection of algorithms and data structures optimized for building decentralize systems..."
edition = "2021"
keywords = ["algorithims"]
license = "MIT"
name = "algae"
readme = "README.md"
repository = "https://github.com/FL03/algae"
version = "0.1.6" # TODO - Update the cargo package version

[features]
default = []
derive = ["algae-derive"]
full = ["default", "derive", "macros"]
macros = ["algae-macros"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
blake2 = "0.10.4"
bson = ">=2.3.0"
config = "0.13.1"
digest = "0.10.3"
glob = "0.3.0"
hex = "0.4.3"
log = "0.4.17"
sha2 = "0.10.2"
serde = { features = ["derive"], version = ">=1.0.137" }

[build-dependencies]
algae-derive = { optional = true, path = "../derive", version = "0.1.4" }
algae-macros = { optional = true, path = "../macros", version = "0.1.4" }