[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)", "Scattered-Systems (https://gitlab.com/scsys)"]
categories = []
description = "Algae is a collection of core algorithms and data-structures, written in Rust"
edition = "2021"
homepage = "https://github.com/scattered-systems/algae/wiki"
keywords = ["algorithms", "data-structures"]
license = "MIT"
name = "algae-graph"
readme = "README.md"
repository = "https://github.com/scattered-systems/algae"
version = "0.1.15" # TODO - Update the cargo package version

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]

[dev-dependencies]

[dependencies]
itertools = "0.10.5"
<<<<<<< Updated upstream
scsys = { features = ["full"], version = "0.1.28" }
=======
scsys = { features = ["full"], version = "0.1.32" }
>>>>>>> Stashed changes
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.88"