[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)", "Scattered-Systems (https://gitlab.com/scsys)"]
categories = []
description = "Algae is a collection of core algorithms and data-structures, written in Rust"
edition = "2021"
homepage = "https://github.com/scattered-systems/algae/wiki"
keywords = ["algorithms", "data-structures"]
license = "Apache-2.0"
name = "algae-graph"
readme = "README.md"
repository = "https://github.com/scattered-systems/algae"
version = "0.1.17" # TODO - Update the cargo package version

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]

[dev-dependencies]

[dependencies]
decanter = { features = ["derive"], version = "0.1.2" }
scsys = { features = ["full"], version = "0.1.40" }

itertools = "0.10.5"
serde = { features = ["derive"], version = "1" }
serde_json = "1"
