[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "algae-graph"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "std"
]

full = [
    "default",
    "serde",
]

# ********* [FF] Dependencies *********
alloc = [
    "serde?/alloc",
    "strum/alloc",
]

serde = [
    "dep:serde",
]

# ********* [FF] Environments *********
std = [
    "alloc",
    "serde?/std",
    "strum/std",
]

wasm = []

wasi = []

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[build-dependencies]

[dependencies]
itertools.workspace = true
smart-default.workspace = true
thiserror = "1"

[dependencies.serde]
default-features = false
optional = true
features = ["derive"]
version = "1"

[dependencies.strum]
default-features = false
features = ["derive"]
version = "0.26"

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
