[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)", "Scattered-Systems (https://gitlab.com/scsys)"]
categories = []
description = "algae-mmr implements a general merkle mountain range intended for use in blockchain environments"
edition = "2021"
homepage = "https://github.com/scattered-systems/algae/wiki"
keywords = ["algorithms", "data-structures"]
license = "Apache-2.0"
name = "algae-mmr"
readme = "README.md"
repository = "https://github.com/scattered-systems/algae"
version = "0.1.17" # TODO - Update the cargo package version

[features]


[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
decanter = { features = ["derive"], version = "0.1.2" }

anyhow = "1"
digest = "0.10"
hex = "0.4"
itertools = "0.10"
serde = { features = ["derive"], version = "1" }
serde_json = "1"

[dev-dependencies]
scsys = { default-features = false, features = ["gen"], version = "0.1.40" }
hex-literal = "0.3.4"
vrf = "0.2.4"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]