[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)", "Scattered-Systems (https://gitlab.com/scsys)"]
categories = []
description = "algae-mmr implements a general merkle mountain range intended for use in blockchain environments"
edition = "2021"
homepage = "https://github.com/scattered-systems/algae/wiki"
keywords = ["algorithms", "data-structures"]
license = "MIT"
name = "algae-mmr"
readme = "README.md"
repository = "https://github.com/scattered-systems/algae"
version = "0.1.15" # TODO - Update the cargo package version

[features]


[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
digest = "0.10.5"
hex = "0.4.3"
itertools = "0.10.5"
<<<<<<< Updated upstream
scsys = { features = ["full"], version = "0.1.28" }
=======
scsys = { features = ["full"], version = "0.1.32" }
>>>>>>> Stashed changes
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.88"

[dev-dependencies]
hex-literal = "0.3.4"
vrf = "0.2.4"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]