[package]
authors.workspace = true
build = "build.rs"
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "algae-core"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "std"
]

full = []

# ********* [FF] Dependencies *********
alloc = []

serde = [
    "dep:serde",
]

# ********* [FF] Environment *********
std = [
    "alloc",
    "serde?/std",
    "strum/std",
]

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[build-dependencies]

[dependencies]
strum.workspace = true

[dependencies.serde]
default-features = false
optional = true
features = ["derive"]
version = "1"

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
