name: Clippy

on:
  pull_request:
    branches-ignore: ["beta*", "dev*", "next*"]
  push:
    branches-ignore: ["beta*", "dev*", "next*"]
    tags: ["nightly*", "v*.*.*"]
  release:
  schedule:
    - cron: "30 21 * * *" # 9:30pm UTC
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  clippy:
    name: Clippy

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - name: Setup
        run: cargo install clippy-sarif sarif-fmt
      - name: clippy
        run: cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
