name: Publish

concurrency: 
  cancel-in-progress: true
  group: ${{ github.event.repository.name }}

env:
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

permissions: write-all

jobs:
  base:
    name: Publish (core)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [ core ]
    env:
      PACKAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.feature }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{env.PACKAGE_NAME}})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  features:
    name: Publish (features)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [ graph, merkle, mmr, queue ]
    env:
      PACKAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.feature }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{env.PACKAGE_NAME}})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    name: Publish (sdk)
    needs: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish (sdk)
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}