name: Rust

on:
  push:
    branches:
      - master
    tags:
      - latest
  pull_request:
    tags:
      - latest

env:
  CARGO_TERM_COLOR: always

jobs:
  crate:
    env:
      CARGO_PKG_NAME: algae
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test --workspace --verbose --color $CARGO_TERM_COLOR
      - name: Build and Push
        run: cargo publish --all-features --package $CARGO_PKG_NAME --token ${{ secrets.CARGO_REGISTRY_TOKEN }}