name: Rust

concurrency: 
  cancel-in-progress: false
  group: ${{ github.event.repository.name }}-rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ "main", "v*.*.*" ]
  push:
    branches: [ "main" ]
    tags: [ "nightly*",  "v*.*.*" ]
  release:
  repository_dispatch:
    types: [ rust ]
  schedule:
    - cron: "30 21 * * *" # 9:30pm UTC
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        target: [ wasm32-unknown-unknown, wasm32-wasi ]
        toolchain: [ stable, nightly ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup (langspace)
        run: |
          rustup update
          rustup default ${{ matrix.toolchain }}
      - name: Set target (${{ matrix.target }})
        if: matrix.toolchain == 'nightly'
        run: rustup target add ${{ matrix.target }}
      - name: Build

        run: cargo build -r -v --workspace
      - name: Cache build
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release
      - name: Test
        run: cargo test --all-features -r -v --workspace
      - name: Bench
        if: matrix.toolchain == 'nightly'
        run: cargo bench --all -v
  nightly:
    name: Nightly
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        target: [ wasm32-unknown-unknown, wasm32-wasi ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup (langspace)
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup update
      - name: Set target (${{ matrix.target }})
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build -r -v --workspace --target ${{ matrix.target }}
      - name: Cache build
        uses: actions/cache@v3
        with:
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release
      - name: Test
        run: cargo test --all-features -r -v --workspace --target ${{ matrix.target }}
      - name: Bench
        run: cargo bench --all -v --target ${{ matrix.target }}