name: Rust

on:
  push:
    branches: [ "master" ]
    tags: [ "latest" ]
  pull_request:
    branches: [ "master" ]
    tags: [ "latest" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: cargo test --workspace --verbose --color $CARGO_TERM_COLOR
  derive:
    env:
      CARGO_PKG_NAME: algae
    runs-on: ubuntu-latest
    needs: [ login, test ]

    steps:
      - name: Build and Push
        run: cargo publish -p $CARGO_PKG_NAME --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  macros:
    env:
      CARGO_PKG_NAME: algae
    runs-on: ubuntu-latest
    needs: [ login, test ]
    steps:
      - name: Build and Push
        run: cargo publish -p $CARGO_PKG_NAME --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  crate:
    env:
      CARGO_PKG_NAME: algae
    runs-on: ubuntu-latest
    needs: [ derive, macros, login, test ]
    steps:
      - name: Build and Push
        run: cargo publish -p $CARGO_PKG_NAME --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }}