name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches-ignore: [ "dev*" ]
    tags: [ "v*.*.*" ]
  push:
    branches-ignore: [ "dev*" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: rustup default ${{ matrix.toolchain }}
      - run: cargo build --release -v --workspace
      - run: cargo test --all --all-features --release -v
  features:
    if: ${{ github.event.inputs.publish }}
    name: Features
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - algae-graph
          - algae-merkle
          - algae-mmr
    steps:
      - uses: actions/checkout@v3
      - name: Publish (${{matrix.package}})
        run: cargo publish --all-features -v -p ${{ matrix.package }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    if: ${{ github.event.inputs.publish }}
    name: Publish
    needs: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish (algae)
        run: cargo publish --all-features -v -p algae --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
