name: Rust

on:
  push:
    branches: [ "master", "latest" ]
  pull_request:
    branches: [ "latest" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  crate:
    env:
      CARGO_PKG_NAME: algae
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test -p $CARGO_PKG_NAME --all-features -v --color $CARGO_TERM_COLOR
      - name: Build and Push
        run: cargo publish -p $CARGO_PKG_NAME --all-features -v --color $CARGO_TERM_COLOR