name: Rust

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

env:
  CARGO_TERM_COLOR: always

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo login ${CARGO_REGISTRY_TOKEN}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose --workspace
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --all-features --release --verbose
  publish:
    needs: [ build, login, test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish
      run: |
        cargo publish -p algae-core --jobs 1
        cargo publish -p algae-derive --jobs 1
        cargo publish -p algae-macros --jobs 1
        cargo publish -p algae-merkle --jobs 1
        cargo publish -p algae --all-features --jobs 1
